apiVersion: v1
kind: Service
metadata:
  name: sample-cicd-app
  namespace: production
  labels:
    app: sample-cicd-app
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 3000
    nodePort: 30500
    protocol: TCP
  selector:
    app: sample-cicd-app
